# Generated by Django 4.1.2 on 2022-11-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroVariaveisDecisao', models.IntegerField(blank=True)),
                ('numeroRestricoes', models.IntegerField(blank=True)),
            ],
        ),
    ]
